spring:
  redis:
    host: 192.168.127.9
    port: 6379       # Redis服务器连接端口
#    database: 0      # Redis数据库索引（默认为0）
#    password:        # Redis服务器连接密码（默认为空）
#    timeout: 0       # 连接超时时间（毫秒）
#    pool:
#      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
#      max-idle: 8    # 连接池中的最大空闲连接
#      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      min-idle: 0    # 连接池中的最小空闲连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.127.9:3306/travel?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect   #设置引擎为 InnoDB （默认使用 MyISAM）
        #          storage_engine: innodb                             #这种方式推荐，但没有生效，暂且用上面的配置
        show_sql: true             #打印执行的SQL
        format_sql: true           #让打印的SQL可读性更佳
        jdbc:
          batch_size: 500
    #        generate_statistics: true  #性能分析
    #        use_sql_comments: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info